name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd django_app
        python manage.py test
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true
        
    - name: Verify deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 60
        
    - name: Send deployment notification
      if: success()
      run: |
        echo "Deployment to Render completed successfully!"
        # Add notification logic here (e.g., Slack, email)
        
    - name: Deployment failed
      if: failure()
      run: |
        echo "Deployment to Render failed!"
        # Add failure notification logic here
